#======================================================
# PENGATURAN SITUS UTAMA
#======================================================
# Informasi dasar yang digunakan di seluruh situs.
# Dapat diakses menggunakan {{ site.title }}, {{ site.description }}, dll.

title: PKC PMII Bali Nusra
email: pmiibalinusra.official@gmail.com
description: >- # Tanda >- mengabaikan baris baru, bagus untuk deskripsi panjang.
  Website Resmi Pengurus Koordinator Cabang (PKC) Pergerakan Mahasiswa Islam Indonesia (PMII) Bali-Nusa Tenggara.
  Mendorong inovasi dan pergerakan mahasiswa yang berlandaskan Ahlussunnah wal Jama'ah.

# URL lengkap situs Anda untuk produksi. PASTIKAN BENAR.
# Tanpa garis miring (/) di akhir.
url: "https://pmiibalinusra.or.id"
# Biarkan kosong ("") karena situs berada di root domain.
baseurl: ""

#======================================================
# PENGATURAN MEDIA SOSIAL
#======================================================
# Mendefinisikan link media sosial di satu tempat agar mudah diubah.
# Dapat diakses menggunakan {{ site.social.youtube }}, dll.

social:
  youtube: https://youtube.com/@pkcpmiibalinusra
  facebook: https://facebook.com/pkcpmiibalinusatenggara
  instagram: https://instagram.com/pkc.pmiibalinusra

#======================================================
# PENGATURAN BUILD
#======================================================

# Karena Anda menggunakan layout HTML kustom dengan Tailwind CSS,
# tema Jekyll (seperti Minima) tidak diperlukan. `theme: null` adalah pengaturan yang benar.
theme: null

# Plugin yang digunakan untuk fungsionalitas tambahan.
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Plugin ini akan menangani semua tag Open Graph & Twitter Card.

# Aturan untuk membuat URL postingan yang rapi dan SEO-friendly.
permalink: /rilis/:year/:month/:day/:title

#======================================================
# EXCLUDE (PENGECUALIAN)
#======================================================
# Daftar file dan folder yang TIDAK akan diproses oleh Jekyll.
# Ini penting untuk menjaga kebersihan folder hasil build (_site).

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
